In [1]:
import numpy as np
import pandas as pd

In [3]:
!python -V

Python 3.9.17


In [4]:
# You can get the version information using the __version__ field
np.__version__

'1.24.3'

In [7]:
# getting the data
# wget "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"

In [8]:
df = pd.read_csv("./data.csv")

In [9]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [11]:
# Question 2: How many records are in the dataset?
df.describe()
df.Year.count()   # 11914
df.isnull().sum() # Year has 0 null values
# Answer 11914

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [12]:
df.Year.count()

11914

In [13]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [22]:
# Question 3: Who are the most frequent car manufacturers (top-3) according to the dataset?
#df.Make
#df.Make.nunique()    # 48
df.groupby('Make').Model.describe().sort_values(by=['count'], ascending=False)
# Answer Chevrolet, Ford, Volkswagen

count unique                 top freq
Make                                               
Chevrolet      1123     63      Silverado 1500  156
Ford            881     51               F-150  126
Volkswagen      809     31  Beetle Convertible   89
Toyota          746     39              Tundra  140
Dodge           626     33              Dakota   65
Nissan          558     32            Frontier   76
GMC             515     30         Sierra 1500   90
Honda           449     21              Accord   75
Mazda           423     31                   3   53
Cadillac        397     30                 CTS   42
Mercedes-Benz   353     40             E-Class   49
Suzuki          351     16                 XL7   39
BMW             334     39            3 Series   34
Infiniti        330     38                 Q50   36
Audi            328     34                  A3   47
Hyundai         303     22              Sonata   36
Volvo           281     26                XC60   54
Subaru          256     16             Impreza   34
Acura           252     18                 MDX   34
Kia             231     16             Sorento   38
Mitsubishi      213     22     Outlander Sport   28
Lexus           202     46              LS 460   14
Buick           196     20              Encore   28
Chrysler        187     19                 300   30
Pontiac         186     20                  G6   22
Lincoln         164     16                 MKZ   24
Oldsmobile      150     18               Alero   24
Land Rover      143     11         Range Rover   35
Porsche         136     12                 911   58
Saab            111      8                 9-3   32
Aston Martin     93     12          V8 Vantage   32
Plymouth         82     10                Colt   19
Bentley          74     18      Continental GT   19
Ferrari          69     14                 360   13
FIAT             62      5                 500   28
Scion            60      8                  tC   14
Maserati         58      8        Quattroporte   13
Lamborghini      52      6            Gallardo   25
Rolls-Royce      31     10               Ghost    6
Lotus            29      5               Evora   10
Tesla            18      1             Model S   18
HUMMER           17      2                  H3   10
Maybach          16      3                  57    7
McLaren           5      4             MP4-12C    2
Alfa Romeo        5      1                  4C    5
Spyker            3      1                  C8    3
Bugatti           3      1         Veyron 16.4    3
Genesis           3      1                 G80    3

In [ ]:
# Question 4: What's the number of unique Audi car models in the dataset?
# Answer: 34

In [32]:
audis = df[
    df.Make == 'Audi'
]
audis.nunique()

Make                   1
Model                 34
Year                  20
Engine Fuel Type       5
Engine HP             40
Engine Cylinders       6
Transmission Type      3
Driven_Wheels          2
Number of Doors        2
Market Category       15
Vehicle Size           3
Vehicle Style          6
highway MPG           23
city mpg              18
Popularity             1
MSRP                 234
dtype: int64

In [34]:
audis['Model'].describe()

count     328
unique     34
top        A3
freq       47
Name: Model, dtype: object

In [36]:
audis.groupby('Model').Model.describe().sort_values(by=['count'], ascending=False)

count unique              top freq
Model                                             
A3                 47      1               A3   47
A4                 25      1               A4   25
R8                 25      1               R8   25
A6                 23      1               A6   23
Q5                 20      1               Q5   20
100                15      1              100   15
Q7                 15      1               Q7   15
Q3                 14      1               Q3   14
S4                 12      1               S4   12
A7                 10      1               A7   10
90                  9      1               90    9
S5                  9      1               S5    9
A5                  9      1               A5    9
allroad             8      1          allroad    8
allroad quattro     8      1  allroad quattro    8
SQ5                 6      1              SQ5    6
200                 6      1              200    6
RS 5                6      1             RS 5    6
80                  6      1               80    6
S3                  6      1               S3    6
A8                  6      1               A8    6
TT                  6      1               TT    6
S6                  5      1               S6    5
TTS                 4      1              TTS    4
S7                  4      1               S7    4
S8                  4      1               S8    4
V8                  3      1               V8    3
RS 4                3      1             RS 4    3
Cabriolet           3      1        Cabriolet    3
A4 allroad          3      1       A4 allroad    3
RS 7                3      1             RS 7    3
TT RS               2      1            TT RS    2
Coupe               2      1            Coupe    2
RS 6                1      1             RS 6    1

In [37]:
# Question 5: How many columns in the dataset have missing values?
df.isnull().sum()
# Answer: 5

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [38]:
# Question 6:
#
#    Find the median value of "Engine Cylinders" column in the dataset.
#    Next, calculate the most frequent value of the same "Engine Cylinders".
#    Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
#    Now, calculate the median value of "Engine Cylinders" once again.
#
# Has it changed?
# Answer: 5.628828677213059 vs. 5.624727211683734 --> not really
df['Engine Cylinders'].mean()

5.628828677213059

In [39]:
df['Engine Cylinders'].describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [45]:
df['Engine Cylinders'].nunique()

9

In [48]:
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [50]:
df['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [52]:
df['Engine Cylinders'].fillna(4.0).mean()

5.624727211683734

In [53]:
# Question 7
#
#    Select all the "Lotus" cars from the dataset.
#    Select only columns "Engine HP", "Engine Cylinders".
#    Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
#    Get the underlying NumPy array. Let's call it X.
#    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#    Compute the inverse of XTX.
#    Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
#    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#    What's the value of the first element of w?
#


In [62]:
lotus = df[
    df.Make == 'Lotus'
]
X = lotus[['Engine HP', 'Engine Cylinders']].drop_duplicates().values

In [63]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [78]:
XTX = (X.T).dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [79]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [80]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [84]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(X.T)
w = w.dot(y)
w
#    What's the value of the first element of w?
# Answer 4.59494481

array([  4.59494481, -63.56432501])